version: 2
updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: daily
      time: "22:00"
    allow:
      - dependency-type: "direct"
    open-pull-requests-limit: 10
    target-branch: "dev"
